depreciation_and_amortization = [
 'Depreciation and amortization'
,'Depreciation Depletion And Amortization'
,'Depreciation Depletion And Amortization Including Discontinued Operation Depreciationand Amortization'
,'Depreciation Amortization And Accretion Net'
,'Depreciation, amortization, and other'
,'Depreciation, amortization and impairment'
,'Depreciation and amortization expense'
,'Depreciation of property and equipment'
,'Depreciation And Impairment On Disposition Of Property And Equipment'
,'Depreciationand Impairmenton Dispositionof Propertyand Equipment'
,'Depreciation and impairment of property and equipment'
,'Depreciation and tooling amortization'
,'Depreciation and amortization of property and equipment and capitalized content costs, operating lease assets, and other'
,'Depreciation'
]

stock_based_compensation = [
 'Share-based compensation expense'
,'Share Based Compensation'
,'Stock-based compensation expense'
,'Stock-based compensation'
,'Share-based compensation'
]

cash_from_operations = [
    'Cash generated by operating activities'
    ,'Net cash provided by operating activities'
    ,'Net cash provided by/(used in) operating activities'
    ,'Net cash provided by (used for) operating activities'
    ,'Net Cash Provided By Used In Operating Activities'
    ,'Net Cash Provided By Used In Operating Activities Continuing Operations'
    ,'Net cash from operations'
    ,'Net Cash Provided by (Used in) Operating Activities'
    ,'Net cash used in operating activities'
]

#  PURCHASE OF PROPERTY, PLANT AND EQUIPMENT
capital_expenditure = [
 'Purchases of property, plant and equipment'
,'Payments To Acquire Property Plant And Equipment'
,'Purchases of investments'
,'Capital expenditures - excluding equipment leased to others'
,'Purchases of property and equipment'
,'Purchases of property and equipment excluding finance leases, net of sales'
,'Purchases of property and equipment excluding capital leases'
,'Capital expenditures'
,'Acquisition of property and equipment included in accounts payable and accrued liabilities'
,'Capital expenditures – excluding equipment leased to others'
,'Payments To Acquire Productive Assets'
,'Payments To Acquire Productive Assets'
,'Purchases of property and equipment excluding finance leases, net of sales'
,'Purchases of property and equipment excluding capital leases, net of sales'
,'Capital spending'
,'Payments For Proceeds From Productive Assets'
,'Additions to property, plant, and equipment'
]

#Acquisitions Of Companies and Assets
cash_acquisitions = [
 'Acquisitions of businesses, net of cash acquired'
,'Payments To Acquire Businesses Net Of Cash Acquired'
,'Acquisition of companies, net of cash acquired, and purchases of intangible and other assets'
,'Investments and acquisitions (net of cash acquired)'
,'Business combinations, net of cash acquired'
,'Net cash used in investing activitie'
,'Acquisitions, net of cash acquired'
,'Acquisitions, net of cash acquired, and purchases of intangible assets'
,'Acquisitions Net Of Cash Acquired And Purchases Of Intangible And Other Assets'
,'Acquisitions of finance receivables and operating leases'
,'Payments To Acquire Productive Assets'
,'Acquisitions, net of cash acquired, non-marketable investments, and other'
,'Payments To Acquire Businesses Net Of Cash Acquired And Othe'
,'Acquisitions of businesses and intangible assets'
,'Payments To Acquire Businesses Net Of Cash Acquired And Purchases Of Intangible And Other Assets'
]

##### SHORT DEBT #######
short_term_debt_new = [
 'Proceeds from short-term borrowings'
,'Proceeds From Short Term Debt'
,'Increase/(decrease) in short-term borrowings, net'
,'(Decrease)/increase in short-term borrowings, net'
,'Short-term borrowings – net (original maturities three months or less)'
,'Proceeds from short-term debt, and other'
]
short_term_debt_payments = [
 'Payments on short-term borrowings'
,'Principal payments on short-term borrowings '
,'Repayments Of Short Term Debt'
,'Increase/(decrease) in short-term borrowings, net'
,'(Decrease)/increase in short-term borrowings, net'
,'Repayments of short-term debt, and other'
]

##### LONG DEBT #######
long_term_debt_new = [
 'Proceeds from issuances of long-term debt'
,'Proceeds from issuance of long-term debt'
,'Proceeds From Issuance Of Long Term Debt'
,'Proceeds from issuance of long-term debt—senior notes, net of discount'
,'Proceeds from issuance of long-term debt—senior notes, net of discount and fees'
,'Proceeds From Issuance Of Senior Long Term Debt'
,'Proceeds from issuance of debt, net of costs'
,'Proceeds From Debt Net Of Issuance Costs'
,'Proceeds from debt issued (original maturities greater than three months):'
,'Proceeds from issuances of convertible and other debt'
,'Proceeds from issuance of convertible and other debt'
,'Proceeds from issuances of debt'
,'Proceeds from issuance of convertible debt'
,'Proceeds from long-term debt'
,'Proceeds from issuance of long-term debt, net'
]
long_term_debt_payments = [
 'Payments on long-term debt'
,'Principal payments on long-term debt'
,'Repayments Of Long Term Debt'
,'Principal payments on long-term debt'
,'Repayments Of Assumed Debt'
,'Repayments of debt'
,'Payments on debt (original maturities greater than three months):'
,'Repayments of convertible and other debt'
,'Repayments of long-term debt'
,'Principal payments on finance leases'
]

interest_paid = [
'Interest Paid'
,'Cash paid for interest, net of amounts capitalized'
,'Interest Paid Net'
,'Interest Paid On Long Term Debt'
,'Cash paid for interest'
,'Cash paid during the period for interest, net of amounts capitalized'
]

issuance_of_common_stock = [
'Common stock issued, including treasury shares reissued'
,'Proceeds from issuances of common stock in public offerings, net of issuance costs'
,'Proceeds from issuances of common stock in public offerings, net of underwriting discounts'
,'Proceeds from issuance of common stock in public offering'
,'Proceeds from exercises of stock options and other stock issuances'
,'Common stock issued'
]

repurchase_of_common_stock = [
'Repurchases of capital stock'
,'Purchases of treasury stock'
,'Repurchases of stock'
,'Payments For Repurchase Of Common Stock'
,'Common shares repurchased'
,'Common stock repurchased'
,'Purchases of common stock'
,'Common stock repurchased'
,'Repurchase of common stock'
,'Repurchases of Class A common stock'
]

common_dividends_paid = [
'Cash dividends paid'
,'Payments Of Ordinary Dividends'
,'Dividends paid'
,'Payments Of Dividends Common Stock'
,'Common stock cash dividends paid'
,'Cash payments for dividends and dividend equivalents'
,'Payment of dividends to stockholders'
]

inventory = [
'Inventory'
,'Increase Decrease In Inventories'
,'Inventories'
,'Inventories and operating lease vehicles'
,'Decrease/(Increase) in inventory'
]

# Money Owned by Customers to My Company
accounts_receivable = [
'Accounts receivable'
,'Increase Decrease In Accounts Receivable'
,'Receivables – trade and other'
,'Receivables - trade and other'
,'Increase Decrease In Receivables'
,'Decrease/(Increase) in accounts receivable and other assets'
,'Accounts receivable, net and other'
,'Increase Decrease In Accounts Receivable And Other Operating Assets'
]

# Obligation to pay suppliers or vendors for goods/services received
accounts_payable = [
'Accounts payable'
,'Increase Decrease In Accounts Payable'
,'Accounts payable and accrued liabilities'
,'Accounts payable, accrued and other liabilities'
,'Increase/(Decrease) in accounts payable and accrued and other'
]

# Obligation to deliver goods or services to customers who have paid in advance
customer_advances = [
'Customer advances',
'Unearned revenue'
]

#Expenses yet to pay
obligations = [
'Accrued expenses'
,'Increase Decrease In Accrued Liabilities'
,'Accrued expenses and other'
,'Increase Decrease In Accrued Liabilities And Other Operating Liabilities'
,'Accrued compensation and benefits'
,'Accrued expenses and other current liabilities'
]

wages = [
'Accrued wages, salaries and employee benefit'
,'Accrued wages, salaries and employee benefits'
,'Increase Decrease In Employee Related Liabilities'
]